"""
Django settings for LAST_Hub project.

Generated by 'django-admin startproject' using Django 6.0.2.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

import os
from datetime import datetime
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-rnib3=gd=kqojf^rf&g9-ch-vnm7xvg#s+fgj%2%07s3s)sa0i'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = [
    "localhost",
    "127.0.0.1",
    "10.23.1.25"
]


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'markdownx',
    'hub',
    'controller',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'LAST_Hub.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates']
        ,
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'hub.context_processor.project_info',
                'hub.context_processor.safety_status',
                'hub.context_processor.manual_pages',
                'hub.context_processor.observatory_settings',
                'hub.context_processor.observatory_status',
            ],
        },
    },
]

WSGI_APPLICATION = 'LAST_Hub.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Asia/Jerusalem'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = '/hub/static/'
STATIC_ROOT = BASE_DIR / "staticfiles"
MEDIA_URL = "/hub/media/"
MEDIA_ROOT = BASE_DIR / "media"
MARKDOWNX_URLS_PATH = "/hub/markdownx/markdownify/"
MARKDOWNX_UPLOAD_URLS_PATH = "/hub/markdownx/upload/"
MARKDOWNX_MEDIA_PATH = datetime.now().strftime("markdownx/%Y/%m/%d")
MARKDOWNX_MARKDOWN_EXTENSIONS = [
    "fenced_code",
    "codehilite",
]

FORECAST_URL = "http://10.23.1.16/forecast"
OBS_SAFETY_API_BASE_URL = os.environ.get(
    "OBS_SAFETY_API_BASE_URL",
    "http://10.23.1.25/observatory/safety/api/",
)
CONTROLLER_API_BASE_URL = os.environ.get(
    "CONTROLLER_API_BASE_URL",
    "",
)

OBS_LATITUDE = 30.0529838
OBS_LONGITUDE = 35.0407331

PROJECT_VERSION = "0.2.0"
PROJECT_SOURCE_URL = "https://github.com/sarhabaot/LAST_Hub"

USE_X_FORWARDED_HOST = True

LOGIN_URL = "/hub/accounts/login/"
LOGIN_REDIRECT_URL = "/hub/operations/"
LOGOUT_REDIRECT_URL = "/hub/"
