"""
Django settings for LAST_Hub project.

Generated by 'django-admin startproject' using Django 6.0.2.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

import os
from datetime import datetime
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-rnib3=gd=kqojf^rf&g9-ch-vnm7xvg#s+fgj%2%07s3s)sa0i'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = [
    h.strip()
    for h in os.environ.get("ALLOWED_HOSTS", "localhost,127.0.0.1").split(",")
    if h.strip()
]


# Application definition

INSTALLED_APPS = [
    'jazzmin',
    'admin_tools_stats',
    'django_nvd3',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'markdownx',
    'hub',
    'forecast',
    'safety',
    'checklist',
    'docs',
    'controller',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'LAST_Hub.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates']
        ,
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'hub.context_processor.project_info',
                'hub.context_processor.primary_navigation',
                'hub.context_processor.safety_status',
                'hub.context_processor.observatory_settings',
                'hub.context_processor.observatory_status',
                'hub.context_processor.analytics',
            ],
        },
    },
]

WSGI_APPLICATION = 'LAST_Hub.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': os.environ.get("DB_PATH", BASE_DIR / "db.sqlite3"),
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Asia/Jerusalem'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = '/hub/static/'
STATIC_ROOT = Path(os.environ.get("STATIC_ROOT", BASE_DIR / "staticfiles"))
MEDIA_URL = "/hub/media/"
MEDIA_ROOT = BASE_DIR / "media"
MARKDOWNX_URLS_PATH = "/hub/markdownx/markdownify/"
MARKDOWNX_UPLOAD_URLS_PATH = "/hub/markdownx/upload/"
MARKDOWNX_MEDIA_PATH = datetime.now().strftime("markdownx/%Y/%m/%d")
MARKDOWNX_MARKDOWN_EXTENSIONS = [
    "fenced_code",
    "codehilite",
    "tables",
    "admonition",
]

OBS_SAFETY_API_BASE_URL = os.environ.get(
    "OBS_SAFETY_API_BASE_URL",
    "http://10.23.1.25/observatory/safety/api/",
)

IMS_USERNAME = os.environ.get("IMS_USERNAME", "")
IMS_PASSWORD = os.environ.get("IMS_PASSWORD", "")
IMS_BASE_URL = os.environ.get(
    "IMS_BASE_URL", "https://data.israel-meteo-service.org"
)
IMS_DIRECTORY = os.environ.get("IMS_DIRECTORY", "IMS_ICON")
IMS_DATA_DIR = Path(
    os.environ.get("IMS_DATA_DIR", BASE_DIR / "data" / "forecast")
)
IMS_VERIFY_SSL = os.environ.get("IMS_VERIFY_SSL", "false").lower() == "true"
FORECAST_CACHE_PATH = Path(
    os.environ.get("FORECAST_CACHE_PATH", BASE_DIR / "data" / "forecast.json")
)
FORECAST_RETENTION_DAYS = int(os.environ.get("FORECAST_RETENTION_DAYS", "2"))
MANUAL_DOCS_ROOT = BASE_DIR / "docs" / "manual"
CONTROLLER_API_BASE_URL = os.environ.get(
    "CONTROLLER_API_BASE_URL",
    "http://localhost:8000/controller",
)
CONTROLLER_BACKEND = os.environ.get("CONTROLLER_BACKEND", "mock")
CONTROLLER_MOCK_UNITS = int(os.environ.get("CONTROLLER_MOCK_UNITS", "4"))

UMAMI_SCRIPT_URL = os.environ.get("UMAMI_SCRIPT_URL", "")
UMAMI_WEBSITE_ID = os.environ.get("UMAMI_WEBSITE_ID", "")

OBS_LATITUDE = 30.0529838
OBS_LONGITUDE = 35.0407331

# ---------------------------------------------------------------------------
# Forecast tuning knobs — adjust these to change verdict colors and the
# observation-night display window. Each pair is (marginal threshold, no-go
# threshold): values below the first are "go" (green), between are "marginal"
# (yellow/orange), at or above the second are "no-go" (red).
# ---------------------------------------------------------------------------
FORECAST_CLOUD_THRESHOLDS = (30.0, 60.0)        # % total cloud cover
FORECAST_HUMIDITY_THRESHOLDS = (80.0, 85.0)     # % relative humidity
FORECAST_PRECIP_THRESHOLDS = (0.05, 0.1)        # mm precipitation per step

# Fixed local-time window shown in the forecast view. Astronomical dusk
# (the real start of useful observation) falls inside this range year-round,
# but we display the same hours every night for consistency.
FORECAST_NIGHT_START = "16:00"  # HH:MM local time, evening
FORECAST_NIGHT_END = "06:00"    # HH:MM local time, next morning

PROJECT_VERSION = "0.3.0"
PROJECT_SOURCE_URL = "https://github.com/sarhabaot/LAST_Hub"

USE_X_FORWARDED_HOST = True

LOGIN_URL = "/hub/accounts/login/"
LOGIN_REDIRECT_URL = "/hub/checklist/"
LOGOUT_REDIRECT_URL = "/hub/"
