# Generated by Django 6.0.2 on 2026-02-24 14:26

import django.db.models.deletion
import markdownx.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('organization', models.CharField(blank=True, max_length=120)),
                ('justification', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('denied', 'Denied')], default='pending', max_length=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ManualPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(default='manual', max_length=120, unique=True)),
                ('title', models.CharField(default='Manual', max_length=200)),
                ('section', models.CharField(blank=True, default='', max_length=200)),
                ('content', markdownx.models.MarkdownxField(blank=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='MountConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mount_id', models.CharField(choices=[('M01', 'Mount 01'), ('M02', 'Mount 02'), ('M03', 'Mount 03'), ('M04', 'Mount 04'), ('M05', 'Mount 05'), ('M06', 'Mount 06'), ('M07', 'Mount 07'), ('M08', 'Mount 08'), ('M09', 'Mount 09'), ('M10', 'Mount 10'), ('M11', 'Mount 11'), ('M12', 'Mount 12')], max_length=3, unique=True)),
                ('enabled', models.BooleanField(default=True)),
                ('reason', models.TextField(blank=True, help_text='Reason for disabling this mount (if disabled)')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mount_config_updates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Mount Configuration',
                'verbose_name_plural': 'Mount Configurations',
                'ordering': ['mount_id'],
            },
        ),
        migrations.CreateModel(
            name='OperationalChecklistState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('items', models.JSONField(blank=True, default=dict)),
                ('observatory_state', models.CharField(choices=[('unknown', 'Unknown'), ('open', 'Open'), ('closed', 'Closed')], default='unknown', max_length=12)),
                ('last_action', models.CharField(blank=True, choices=[('open', 'Open'), ('close', 'Close')], max_length=8)),
                ('last_action_status', models.CharField(blank=True, choices=[('success', 'Success'), ('failed', 'Failed'), ('skipped', 'Skipped')], max_length=8)),
                ('last_action_message', models.TextField(blank=True)),
                ('last_action_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_action_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='operations_actions', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='operations_updates', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
