# Generated by Django 6.0.2 on 2026-02-15 00:00

from django.db import migrations, models
import markdownx.models


class Migration(migrations.Migration):

    dependencies = [
        ("hub", "0002_alter_accountrequest_id_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ManualPage",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("slug", models.SlugField(default="manual", max_length=120, unique=True)),
                ("title", models.CharField(default="Manual", max_length=200)),
                ("content", markdownx.models.MarkdownxField(blank=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
