# Generated by Django 6.0.2 on 2026-02-16 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hub", "0003_manual_page"),
    ]

    operations = [
        migrations.AddField(
            model_name="manualpage",
            name="section",
            field=models.CharField(blank=True, default="", max_length=200),
        ),
    ]
